/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "NextJsDashboard2410": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
