/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "MyVpc": {
      "type": "sst.aws.Vpc"
    }
    "NextJsDashboard2410": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "NextjsDB": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
  }
}
